# Generated by Django 2.2.5 on 2019-11-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extensoes', '0002_auto_20191112_0917'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos_Extensoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codextensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extensoes.Extensoes')),
                ('codservico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.Servicos')),
            ],
        ),
    ]
