# Generated by Django 2.2.5 on 2021-01-21 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicoes', '0001_initial'),
        ('avaliadores', '0002_avaliadores_id_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicoes_Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('data_inicial', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativa', models.CharField(default='S', max_length=1)),
                ('id_avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avaliadores.Avaliadores')),
                ('id_instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituicoes.Instituicoes')),
            ],
            options={
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
