# Generated by Django 2.2.5 on 2019-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codregistro', models.PositiveIntegerField()),
                ('codcliente', models.PositiveIntegerField()),
                ('codservico', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data', models.DateTimeField(auto_now=True)),
                ('caminho_arquivo', models.CharField(max_length=255)),
                ('assinatura', models.BinaryField()),
                ('versao', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('codqrcode', models.PositiveIntegerField()),
                ('codindicacao', models.PositiveIntegerField()),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('resumo_obra', models.CharField(max_length=5000)),
            ],
        ),
    ]
