# Generated by Django 2.2.5 on 2019-11-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codregistro', models.PositiveIntegerField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data', models.DateTimeField(auto_now=True)),
                ('assinatura', models.FileField(blank=True, null=True, upload_to='')),
                ('arquivo', models.FileField(upload_to='')),
                ('versao', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('codqrcode', models.PositiveIntegerField(blank=True, null=True)),
                ('codindicacao', models.PositiveIntegerField(blank=True, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('resumo_obra', models.TextField(max_length=5000)),
                ('codcliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Clientes')),
                ('codservico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.Servicos')),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
    ]
