# Generated by Django 2.2.5 on 2019-10-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20191002_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros',
            name='caminho_arquivo',
        ),
    ]
