# Generated by Django 2.2.5 on 2019-11-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20191006_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='codregistro',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
