# Generated by Django 2.2.5 on 2019-11-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20191111_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='codcliente',
            new_name='id_cliente',
        ),
    ]
