# Generated by Django 2.2.5 on 2019-10-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_registros_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='codindicacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registros',
            name='codqrcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registros',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
