# Generated by Django 2.2.5 on 2019-11-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_auto_20191120_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='codusuario',
            new_name='id_usuario',
        ),
    ]
