# Generated by Django 2.2.5 on 2019-10-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_auto_20191005_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='assinatura',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
