# Generated by Django 2.2.5 on 2019-11-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_auto_20191120_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='versao',
            field=models.FloatField(default=1),
        ),
    ]
