# Generated by Django 2.2.5 on 2019-11-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_auto_20191120_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='versao',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
        ),
    ]
