# Generated by Django 2.2.5 on 2019-11-27 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_arquivoregistro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros',
            name='assinatura',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='versao',
        ),
        migrations.AlterField(
            model_name='registros',
            name='arquivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.ArquivoRegistro', verbose_name='arquivo'),
        ),
    ]
