# Generated by Django 2.2.5 on 2019-11-27 15:33

from django.db import migrations, models
import django.utils.timezone
import registros.models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_auto_20191127_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoregistro',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arquivoregistro',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arquivoregistro',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='arquivoregistro',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to=registros.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='arquivoregistro',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
