# Generated by Django 2.2.5 on 2019-11-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_auto_20191127_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='codservico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.Servicos', verbose_name='Serviço'),
        ),
    ]
