# Generated by Django 2.2.5 on 2019-11-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_auto_20191127_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros',
            name='codindicacao',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='codqrcode',
        ),
        migrations.AlterField(
            model_name='registros',
            name='codregistro',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
