# Generated by Django 2.2.5 on 2019-12-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_auto_20191130_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='codindicacao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Código de indicação'),
        ),
    ]
