# Generated by Django 2.2.5 on 2019-12-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_auto_20191201_1708'),
        ('registros', '0014_auto_20191130_1934'),
    ]

    operations = [
    ]
