# Generated by Django 2.2.5 on 2019-12-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_auto_20191201_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoregistro',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
