# Generated by Django 2.2.5 on 2019-12-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0015_merge_20191202_1125'),
        ('registros', '0015_auto_20191203_1114'),
    ]

    operations = [
    ]
