# Generated by Django 2.2.5 on 2019-12-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0016_registros_codigo_promocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoregistro',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
