# Generated by Django 2.2.5 on 2019-12-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0017_arquivoregistro_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros',
            name='codindicacao',
        ),
    ]
