# Generated by Django 2.2.5 on 2019-12-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0016_merge_20191203_1817'),
        ('registros', '0017_arquivoregistro_value'),
    ]

    operations = [
    ]
