# Generated by Django 2.2.5 on 2019-12-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0018_merge_20191205_1005'),
        ('registros', '0018_remove_registros_codindicacao'),
    ]

    operations = [
    ]
