# Generated by Django 2.2.5 on 2019-12-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0019_auto_20191208_1135'),
        ('registros', '0019_merge_20191205_1821'),
    ]

    operations = [
    ]
