# Generated by Django 2.2.5 on 2019-12-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0020_merge_20191209_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivoregistro',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AlterModelOptions(
            name='registros',
            options={'ordering': ('-data',), 'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
    ]
