# Generated by Django 2.2.5 on 2020-01-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0021_registros_manter_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='arquivo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registros.ArquivoRegistro', verbose_name='arquivo'),
        ),
    ]
