# Generated by Django 2.2.5 on 2019-12-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0021_auto_20191214_1602'),
        ('registros', '0020_auto_20191214_1648'),
    ]

    operations = [
    ]
