# Generated by Django 2.2.5 on 2019-12-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0021_registros_manter_arquivo'),
        ('registros', '0022_merge_20191214_1743'),
    ]

    operations = [
    ]
