# Generated by Django 2.2.5 on 2020-01-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0022_auto_20200105_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoregistro',
            name='shar256',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='arquivoregistro',
            name='size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
