# Generated by Django 2.2.5 on 2020-01-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0023_merge_20191227_1114'),
        ('registros', '0023_auto_20200105_1404'),
    ]

    operations = [
    ]
