# Generated by Django 2.2.5 on 2020-01-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0023_auto_20200105_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivoregistro',
            name='shar256',
        ),
        migrations.AddField(
            model_name='arquivoregistro',
            name='b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
