# Generated by Django 2.2.5 on 2020-01-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0024_auto_20200112_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
