# Generated by Django 2.2.5 on 2020-01-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0024_auto_20200112_1551'),
        ('registros', '0024_merge_20200105_1448'),
    ]

    operations = [
    ]
