# Generated by Django 2.2.5 on 2020-01-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0025_registros_excluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoregistro',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo deo registro'),
        ),
    ]
