# Generated by Django 2.2.5 on 2020-01-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0025_merge_20200114_1006'),
        ('registros', '0025_registros_excluido'),
    ]

    operations = [
    ]
