# Generated by Django 2.2.5 on 2020-01-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0026_arquivoregistro_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoregistro',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='content_type'),
        ),
    ]
