# Generated by Django 2.2.5 on 2020-01-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0026_merge_20200115_1843'),
        ('registros', '0027_arquivoregistro_content_type'),
    ]

    operations = [
    ]
