# Generated by Django 2.2.5 on 2020-01-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0028_merge_20200124_1958'),
        ('registros', '0028_arquivoregistro_codregistro'),
    ]

    operations = [
    ]
