# Generated by Django 2.2.5 on 2019-11-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('tipo_servico', models.CharField(blank=True, max_length=1, null=True)),
                ('codservico', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servico', to='servicos.Servicos', verbose_name='Servico')),
            ],
            options={
                'ordering': ('tipo_servico',),
            },
        ),
    ]
