# Generated by Django 2.2.5 on 2019-10-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precos', '0002_auto_20190929_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precos',
            options={'ordering': ('tipo_servico',)},
        ),
    ]
