# Generated by Django 2.2.5 on 2019-10-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codindicacao', models.PositiveIntegerField(null=True)),
                ('nome', models.CharField(max_length=50)),
                ('percentual_promocional', models.DecimalField(max_length=9, decimal_places=2)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
