# Generated by Django 2.2.5 on 2019-10-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_bisavo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo do Bisavó')),
                ('code_avo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo do Avó')),
                ('code_pai', models.CharField(max_length=100, verbose_name='Codigo do Pai')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-data_cadastro',),
            },
        ),
    ]
