# Generated by Django 2.2.5 on 2019-11-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codindicacao', models.PositiveIntegerField(null=True)),
                ('nome', models.CharField(max_length=50)),
                ('percentual_promocional', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
