# Generated by Django 2.2.5 on 2019-11-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicacoes',
            name='codindicacao',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicacoes',
            name='percentual_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
