# Generated by Django 2.2.5 on 2019-10-06 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='filho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
    ]
