# Generated by Django 2.2.5 on 2019-10-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0002_indicacao_filho'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadoPor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
