# Generated by Django 2.2.5 on 2019-09-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0002_remove_indicacoes_percentual_promocional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacoes',
            name='codindicacao',
        ),
    ]
