# Generated by Django 2.2.5 on 2019-11-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20191101_1450'),
        ('indicacoes', '0003_indicadopor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicadoPor',
        ),
        migrations.AlterModelOptions(
            name='indicacoes',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='indicacoes',
            name='filho',
        ),
    ]
