# Generated by Django 2.2.5 on 2019-09-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0003_remove_indicacoes_codindicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicacoes',
            options={'ordering': ('nome',)},
        ),
    ]
