# Generated by Django 2.2.5 on 2019-11-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0002_auto_20191120_1000'),
        ('indicacoes', '0003_merge_20191126_1736'),
    ]

    operations = [
    ]
