# Generated by Django 2.2.5 on 2019-12-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0005_indicacaocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacaocliente',
            name='email_filho',
            field=models.EmailField(default='rando@aleatorio.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicacaocliente',
            name='email_pai',
            field=models.EmailField(default='rando@aleatorio.com', max_length=254),
            preserve_default=False,
        ),
    ]
