# Generated by Django 2.2.5 on 2019-12-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0006_auto_20191214_1728'),
        ('indicacoes', '0005_merge_20191209_1613'),
    ]

    operations = [
    ]
