# Generated by Django 2.2.5 on 2019-12-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confuguracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolar', models.DecimalField(decimal_places=2, default=4, max_digits=5)),
                ('euro', models.DecimalField(decimal_places=2, default=4, max_digits=5)),
                ('credito_inicial', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
            options={
                'verbose_name': 'Confuguracao',
                'verbose_name_plural': 'Confuguracaos',
            },
        ),
    ]
