# Generated by Django 2.2.5 on 2019-12-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_confuguracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confuguracao',
            options={'verbose_name': 'Confuguraçao', 'verbose_name_plural': 'Confugurações'},
        ),
        migrations.AddField(
            model_name='confuguracao',
            name='atualização',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
