# Generated by Django 2.2.5 on 2019-12-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20191214_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='confuguracao',
            name='valor_file',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
    ]
