# Generated by Django 2.2.5 on 2019-11-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20191030_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bonus_indicacao',
            new_name='percentual_promocional',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code_avo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code_bisavo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code_indicacao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code_pai',
        ),
        migrations.AddField(
            model_name='user',
            name='codindicacao',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
