# Generated by Django 2.2.5 on 2020-01-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_confuguracao_valor_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='confuguracao',
            name='pontuacao',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
    ]
