# Generated by Django 2.2.5 on 2020-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_confuguracao_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='confuguracao',
            name='percentual',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='percentual de pontuação'),
        ),
        migrations.AlterField(
            model_name='confuguracao',
            name='pontuacao',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='Valor de resgate'),
        ),
    ]
