# Generated by Django 2.2.5 on 2019-11-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codservico', models.PositiveIntegerField(null=True)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('tamanho', models.PositiveIntegerField()),
                ('medida', models.CharField(blank=True, max_length=5, null=True)),
                ('servico_digitalizacao', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='ServicosExtensoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codservico', models.PositiveIntegerField()),
                ('codextensao', models.PositiveIntegerField()),
            ],
        ),
    ]
