# Generated by Django 2.2.5 on 2019-11-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='codservico',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
