# Generated by Django 2.2.5 on 2019-09-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='codservico',
        ),
    ]
