# Generated by Django 2.2.5 on 2019-11-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicosextensoes',
            name='codextensao',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
