# Generated by Django 2.2.5 on 2019-11-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20191120_1656'),
        ('servicos', '0002_auto_20191121_1143'),
    ]

    operations = [
    ]
