# Generated by Django 2.2.5 on 2019-09-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_remove_servicos_codservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='medida',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='servico_digitalizacao',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
