# Generated by Django 2.2.5 on 2019-11-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20191105_1620'),
        ('servicos', '0002_auto_20191105_2128'),
    ]

    operations = [
    ]
