# Generated by Django 2.2.5 on 2019-12-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_merge_20191126_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='extensoes',
            field=models.ManyToManyField(blank=True, null=True, to='extensoes.Extensoes', verbose_name='Extensoes serviçoes'),
        ),
    ]
