# Generated by Django 2.2.5 on 2019-09-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_auto_20190927_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ('nome',)},
        ),
    ]
