# Generated by Django 2.2.5 on 2019-10-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0005_remove_extensoes_codextensao'),
        ('servicos', '0004_auto_20190930_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicosExtensoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codextensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extensoes.Extensoes')),
                ('codservico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.Servicos')),
            ],
        ),
    ]
