# Generated by Django 2.2.5 on 2019-12-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_auto_20191206_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='extensoes',
            field=models.ManyToManyField(blank=True, to='extensoes.Extensoes', verbose_name='Extensoes serviçoes'),
        ),
    ]
