# Generated by Django 2.2.5 on 2019-10-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_servicosextensoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicosExtensoes',
        ),
    ]
