# Generated by Django 2.2.5 on 2019-10-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_delete_servicosextensoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicosExtensoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codservico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='servicos.Servicos')),
            ],
        ),
    ]
