# Generated by Django 2.2.5 on 2019-12-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_auto_20191206_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ('nome',), 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
