# Generated by Django 2.2.5 on 2019-12-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_auto_20191206_1814'),
        ('servicos', '0004_merge_20191128_1850'),
    ]

    operations = [
    ]
