# Generated by Django 2.2.5 on 2019-12-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_merge_20191206_1917'),
        ('servicos', '0007_auto_20191208_1135'),
    ]

    operations = [
    ]
