# Generated by Django 2.2.5 on 2019-10-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0005_remove_extensoes_codextensao'),
        ('servicos', '0007_servicosextensoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicosextensoes',
            name='codextensao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='extensoes.Extensoes'),
        ),
    ]
