# Generated by Django 2.2.5 on 2019-11-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensoes',
            name='codextensao',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
