# Generated by Django 2.2.5 on 2019-09-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extensoes',
            options={'ordering': ['nome']},
        ),
    ]
