# Generated by Django 2.2.5 on 2019-09-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0002_auto_20190920_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensoes',
            name='codextensao',
        ),
    ]
