# Generated by Django 2.2.5 on 2019-11-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0002_auto_20191112_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensoes',
            name='codextensao',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
