# Generated by Django 2.2.5 on 2019-11-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0003_auto_20191121_1143'),
        ('extensoes', '0003_auto_20191120_1656'),
    ]

    operations = [
    ]
