# Generated by Django 2.2.5 on 2019-09-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0003_remove_extensoes_codextensao'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensoes',
            name='codextensao',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
