# Generated by Django 2.2.5 on 2019-11-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0004_merge_20191126_1736'),
        ('extensoes', '0003_auto_20191120_1000'),
    ]

    operations = [
    ]
