# Generated by Django 2.2.5 on 2019-09-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0004_extensoes_codextensao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensoes',
            name='codextensao',
        ),
    ]
