# Generated by Django 2.2.5 on 2019-12-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0004_merge_20191126_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extensoes',
            options={'ordering': ['nome'], 'verbose_name': 'Extesão', 'verbose_name_plural': 'Extensões'},
        ),
    ]
