# Generated by Django 2.2.5 on 2019-12-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensoes', '0005_merge_20191128_1850'),
        ('extensoes', '0005_auto_20191208_1135'),
    ]

    operations = [
    ]
