# Generated by Django 2.2.5 on 2019-10-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('valor_credito', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('celular', models.CharField(blank=True, max_length=16, null=True)),
                ('data_nascimento', models.DateField(null=True)),
                ('sexo', models.CharField(blank=True, choices=[('', ''), ('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default='', max_length=1, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_pessoa', models.CharField(blank=True, max_length=1, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpjcpf', models.CharField(blank=True, max_length=18, null=True)),
                ('documento_identidade', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('passaporte', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=20, null=True)),
                ('estadocivil', models.CharField(blank=True, max_length=1, null=True)),
                ('biografia', models.CharField(blank=True, max_length=5000, null=True)),
                ('nif', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
