# Generated by Django 2.2.5 on 2019-11-01 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcliente', models.PositiveIntegerField(null=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('valor_credito', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('celular', models.CharField(blank=True, max_length=16, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('', ''), ('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default='', max_length=1, null=True)),
                ('tipo_pessoa', models.CharField(blank=True, choices=[('', ''), ('J', 'Juridica'), ('F', 'Fisica')], max_length=1, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpjcpf', models.CharField(blank=True, max_length=18, null=True)),
                ('senha', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_identidade', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('passaporte', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=20, null=True)),
                ('estadocivil', models.CharField(blank=True, choices=[('C', 'Casado'), ('S', 'Solteiro'), ('D', 'Divorciado'), ('V', 'Viuvo')], max_length=1, null=True)),
                ('biografia', models.TextField(blank=True, max_length=5000, null=True)),
                ('nif', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.URLField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('codindicacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicacao', to='indicacoes.Indicacoes', verbose_name='Indicacao')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
