# Generated by Django 2.2.5 on 2019-11-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcliente', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('valor_credito', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('celular', models.CharField(blank=True, max_length=16, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('', ''), ('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default='', max_length=1, null=True)),
                ('tipo_pessoa', models.CharField(blank=True, choices=[('', ''), ('J', 'Juridica'), ('F', 'Fisica')], max_length=1, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpjcpf', models.CharField(blank=True, max_length=18, null=True)),
                ('senha', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('pais', models.CharField(blank=True, default='Brasil', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='PE', max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_identidade', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('passaporte', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='Brasileiro', max_length=20, null=True)),
                ('estadocivil', models.CharField(blank=True, choices=[('C', 'Casado'), ('S', 'Solteiro'), ('D', 'Divorciado'), ('V', 'Viuvo')], max_length=1, null=True)),
                ('biografia', models.TextField(blank=True, max_length=5000, null=True)),
                ('nif', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.URLField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('confirmation_key', models.CharField(blank=True, default='0', max_length=80, null=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
