# Generated by Django 2.2.5 on 2019-10-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('indicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='codindicacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicacao', to='indicacoes.Indicacao', verbose_name='Indicacao'),
        ),
    ]
