# Generated by Django 2.2.5 on 2019-10-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0002_clientes_codindicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='codusuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='senha',
            field=models.CharField(default='12345', max_length=8),
            preserve_default=False,
        ),
    ]
