# Generated by Django 2.2.5 on 2019-11-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_atuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='atuacao',
            field=models.ManyToManyField(blank=True, to='servicos.Servicos'),
        ),
    ]
