# Generated by Django 2.2.5 on 2019-10-06 20:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0004_auto_20191006_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endreco',
            new_name='Endereco',
        ),
    ]
