# Generated by Django 2.2.5 on 2019-11-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20191102_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='codcliente',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
