# Generated by Django 2.2.5 on 2019-11-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0001_initial'),
        ('clientes', '0004_auto_20191109_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='codindicacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicacao', to='indicacoes.Indicacoes', verbose_name='Indicacao'),
        ),
    ]
