# Generated by Django 2.2.5 on 2019-09-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20190927_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={},
        ),
    ]
