# Generated by Django 2.2.5 on 2019-11-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20191105_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='codcliente',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
