# Generated by Django 2.2.5 on 2019-09-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20190927_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='valor_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
