# Generated by Django 2.2.5 on 2019-11-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20191109_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='senha',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='bairro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cnpjcpf',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='codindicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicacao', to='indicacoes.Indicacoes', verbose_name='Indicacao'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='documento_identidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='PE', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nacionalidade',
            field=models.CharField(default='Brasileiro', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='numero',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(choices=[('', ''), ('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1),
        ),
    ]
