# Generated by Django 2.2.5 on 2019-11-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20191105_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='codindicacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicacao', to='indicacoes.Indicacoes', verbose_name='Indicacao'),
        ),
    ]
