# Generated by Django 2.2.5 on 2019-11-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20191105_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='confirmation_key',
            field=models.CharField(blank=True, default='0', max_length=80, null=True),
        ),
    ]
