# Generated by Django 2.2.5 on 2019-10-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20191006_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='dados_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientes',
            name='endereco_ok',
            field=models.BooleanField(default=False),
        ),
    ]
