# Generated by Django 2.2.5 on 2019-11-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_atuacao', '0002_area_atuacao_codarea'),
        ('clientes', '0008_clientes_confirmation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='atuacao',
            field=models.ManyToManyField(to='area_atuacao.Area_Atuacao'),
        ),
    ]
