# Generated by Django 2.2.5 on 2019-11-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20191115_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='email',
        ),
    ]
