# Generated by Django 2.2.5 on 2019-10-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0003_indicadopor'),
        ('clientes', '0008_auto_20191020_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='codindicacao_por',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicacao_por', to='indicacoes.IndicadoPor', verbose_name='Indicação'),
        ),
    ]
