# Generated by Django 2.2.5 on 2019-10-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_clientes_codindicacao_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='codindicacao_por',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicacao_por', to='indicacoes.IndicadoPor', verbose_name='Indicado por'),
        ),
    ]
