# Generated by Django 2.2.5 on 2019-11-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='bairro',
            field=models.CharField(max_length=50, verbose_name='Bairro *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(max_length=16, verbose_name='Celular *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='Cep *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='Cidade *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cnpjcpf',
            field=models.CharField(max_length=18, verbose_name='CPF/CNPJ *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='codindicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicacao', to='indicacoes.Indicacoes', verbose_name='Como conheceu a gente? *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='documento_identidade',
            field=models.CharField(max_length=50, verbose_name='Documento de identificação *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='documento_tipo',
            field=models.CharField(max_length=20, verbose_name='Tipo de Documento *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='PE', max_length=50, verbose_name='Estado *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estadocivil',
            field=models.CharField(choices=[('C', 'Casado'), ('S', 'Solteiro'), ('D', 'Divorciado'), ('V', 'Viuvo')], max_length=1, verbose_name='Estado civil *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nacionalidade',
            field=models.CharField(default='Brasileiro', max_length=20, verbose_name='Nacionalidade *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='numero',
            field=models.CharField(max_length=8, verbose_name='Número *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50, verbose_name='País de Origem *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(choices=[('', ''), ('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1, verbose_name='Sexo *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_pessoa',
            field=models.CharField(blank=True, choices=[('J', 'Juridica'), ('F', 'Fisica')], max_length=1, null=True, verbose_name='Tipo de Pessoa *'),
        ),
    ]
