# Generated by Django 2.2.5 on 2019-11-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20191115_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='codusuario',
            new_name='id_usuario',
        ),
    ]
