# Generated by Django 2.2.5 on 2019-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20191108_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=50, null=True),
        ),
    ]
