# Generated by Django 2.2.5 on 2019-09-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_remove_clientes_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='telefone',
        ),
    ]
