# Generated by Django 2.2.5 on 2019-09-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20190928_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='celular',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
