# Generated by Django 2.2.5 on 2019-11-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20191021_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='codindicacao_por',
        ),
        migrations.AddField(
            model_name='clientes',
            name='codcliente',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='codindicacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicacao', to='indicacoes.Indicacoes', verbose_name='Indicacao'),
        ),
    ]
