# Generated by Django 2.2.5 on 2019-11-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20191116_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tipo_pessoa',
            field=models.CharField(choices=[('J', 'Juridica'), ('F', 'Fisica')], default='F', max_length=1, verbose_name='Tipo de Pessoa *'),
        ),
    ]
