# Generated by Django 2.2.5 on 2019-11-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20191116_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='codcliente',
            new_name='id_cliente',
        ),
    ]
