# Generated by Django 2.2.5 on 2019-12-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_auto_20191204_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='link_indicacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link de Indicação'),
        ),
    ]
