# Generated by Django 2.2.5 on 2019-12-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_auto_20191204_2211'),
        ('clientes', '0016_auto_20191203_1817'),
    ]

    operations = [
    ]
