# Generated by Django 2.2.5 on 2019-10-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_auto_20190928_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ('nome',)},
        ),
    ]
