# Generated by Django 2.2.5 on 2019-12-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_clientes_link_indicacao'),
        ('clientes', '0017_merge_20191205_1005'),
    ]

    operations = [
    ]
