# Generated by Django 2.2.5 on 2019-12-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_clientes_link_indicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ('nome',), 'verbose_name_plural': 'Clientes'},
        ),
    ]
