# Generated by Django 2.2.5 on 2019-12-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_auto_20191208_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='meu_link_indicacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meu link de Indicação'),
        ),
    ]
