# Generated by Django 2.2.5 on 2019-12-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_merge_20191205_1821'),
        ('clientes', '0018_auto_20191208_1135'),
    ]

    operations = [
    ]
