# Generated by Django 2.2.5 on 2019-12-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_clientes_meu_link_indicacao'),
        ('clientes', '0019_merge_20191209_1613'),
    ]

    operations = [
    ]
