# Generated by Django 2.2.5 on 2019-12-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_clientes_meu_link_indicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='codindicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicacao', to='indicacoes.Indicacoes', verbose_name='Como conheceu a Hoodid.com? *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='documento_identidade',
            field=models.CharField(max_length=50, verbose_name='Número do Documento de Identificação *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='documento_tipo',
            field=models.CharField(choices=[('RG', 'RG'), ('CNH', 'CNH'), ('Seguro Social', 'Seguro Social'), ('Titulo de Eleitor', 'Titulo de Eleitor'), ('Conselho de Classe', 'Conselho de Classe'), ('Outros', 'Outros')], max_length=20, verbose_name='Tipo de Documento de Identificação *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='homepage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
