# Generated by Django 2.2.5 on 2020-01-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_auto_20191219_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='documento_identidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento de Identificação *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='documento_tipo',
            field=models.CharField(blank=True, choices=[('RG', 'RG'), ('CNH', 'CNH'), ('Seguro Social', 'Seguro Social'), ('Titulo de Eleitor', 'Titulo de Eleitor'), ('Conselho de Classe', 'Conselho de Classe'), ('Outros', 'Outros')], max_length=20, null=True, verbose_name='Tipo de Documento de Identificação *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estadocivil',
            field=models.CharField(blank=True, choices=[('C', 'Casado'), ('S', 'Solteiro'), ('D', 'Divorciado'), ('V', 'Viuvo')], max_length=1, null=True, verbose_name='Estado civil *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1, null=True, verbose_name='Sexo *'),
        ),
    ]
