# Generated by Django 2.2.5 on 2019-12-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_auto_20191219_0932'),
        ('clientes', '0020_merge_20191214_1744'),
    ]

    operations = [
    ]
