# Generated by Django 2.2.5 on 2020-01-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_auto_20200124_1754'),
        ('clientes', '0021_merge_20191227_1114'),
    ]

    operations = [
    ]
