# Generated by Django 2.2.5 on 2020-01-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_clientes_pontuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='pontuacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
