# Generated by Django 2.2.5 on 2020-01-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_clientes_pontuacao'),
        ('clientes', '0025_auto_20200124_1958'),
    ]

    operations = [
    ]
