# Generated by Django 2.2.5 on 2020-06-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_auto_20200127_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cnpjcpf',
            field=models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ '),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='documento_tipo',
            field=models.CharField(blank=True, choices=[('RG', 'RG'), ('CNH', 'CNH'), ('Seguro Social', 'Seguro Social'), ('Titulo de Eleitor', 'Titulo de Eleitor'), ('Conselho de Classe', 'Conselho de Classe'), ('Outros', 'Outros'), ('NIF', 'NIF')], max_length=20, null=True, verbose_name='Tipo de Documento de Identificação *'),
        ),
    ]
