# Generated by Django 2.2.5 on 2020-01-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_merge_20200127_1527'),
        ('clientes', '0025_auto_20200127_1530'),
    ]

    operations = [
    ]
