# Generated by Django 2.2.5 on 2020-09-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_auto_20200601_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado *'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nacionalidade',
            field=models.CharField(default='', max_length=20, verbose_name='Nacionalidade *'),
        ),
    ]
