# Generated by Django 2.2.5 on 2020-11-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_auto_20200922_1032'),
        ('clientes', '0027_merge_20200127_1532'),
    ]

    operations = [
    ]
