# Generated by Django 2.2.5 on 2019-11-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes_Atuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Clientes')),
                ('codservico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.Servicos', verbose_name='Serviço')),
            ],
        ),
    ]
