# Generated by Django 2.2.5 on 2019-10-20 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0002_auto_20191020_1005'),
        ('area_atuacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes_Atuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codatuacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area_atuacao.Area_Atuacao', verbose_name='Área de Interesse')),
                ('codcliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('codservico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.Servicos', verbose_name='Serviço')),
            ],
        ),
    ]
