# Generated by Django 2.2.5 on 2019-11-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_atuacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes_atuacao',
            name='codatuacao',
        ),
    ]
