# Generated by Django 2.2.5 on 2019-12-01 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registros', '0014_auto_20191201_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros_Coautores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcoautor', models.PositiveIntegerField(null=True)),
                ('codregistro', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=100)),
                ('percentual_obra', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Coautores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('percentual_obra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.ArquivoRegistro', verbose_name='Arquivo')),
            ],
        ),
    ]
