# Generated by Django 2.2.5 on 2019-12-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_auto_20191201_1708'),
        ('registros_coautores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coautores',
            name='arquivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registros.ArquivoRegistro', verbose_name='Arquivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coautores',
            name='documento',
            field=models.CharField(max_length=50),
        ),
    ]
