# Generated by Django 2.2.5 on 2019-10-07 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data', models.DateTimeField(auto_now=True)),
                ('forma_pagamento', models.CharField(max_length=10)),
                ('autorizado', models.BooleanField(max_length=1)),
                ('codigo_compra_cielo', models.CharField(blank=True, default='0', max_length=80, null=True)),
                ('transacao_cielo', models.CharField(blank=True, max_length=80, null=True)),
                ('msg_cielo', models.CharField(blank=True, max_length=150, null=True)),
                ('codcliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
