# Generated by Django 2.2.5 on 2019-11-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data', models.DateTimeField(auto_now=True)),
                ('forma_pagamento', models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito')], max_length=30)),
                ('autorizado', models.BooleanField(default=False)),
                ('codigo_compra_cielo', models.CharField(blank=True, default='0', max_length=80, null=True)),
                ('transacao_cielo', models.CharField(blank=True, max_length=80, null=True)),
                ('msg_cielo', models.CharField(blank=True, max_length=150, null=True)),
                ('codcliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Clientes')),
            ],
        ),
    ]
