# Generated by Django 2.2.5 on 2019-11-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compras_codcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compras',
            name='forma_pagamento',
            field=models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito')], max_length=30),
        ),
    ]
