# Generated by Django 2.2.5 on 2019-12-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20191204_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
