# Generated by Django 2.2.5 on 2019-11-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos_Promocionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codpromocao', models.PositiveIntegerField(blank=True, null=True)),
                ('promotor', models.CharField(blank=True, max_length=255, null=True)),
                ('qrcode', models.CharField(blank=True, max_length=255, null=True)),
                ('data_emissao', models.DateTimeField(auto_now=True)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('data_resgate', models.DateTimeField(blank=True, null=True)),
                ('cnpjcpf', models.CharField(blank=True, max_length=18, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True)),
                ('id_cliente', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
