# Generated by Django 2.2.5 on 2019-12-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigos_promocionais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigos_promocionais',
            options={'ordering': ('nome',), 'verbose_name': 'Código promocional', 'verbose_name_plural': 'Códigos promocionais'},
        ),
    ]
