# Generated by Django 2.2.5 on 2020-09-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos_promocionais', '0003_auto_20191208_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepromocionalcode',
            name='id_servico',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
