# Generated by Django 2.2.5 on 2020-09-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos_promocionais', '0004_generatepromocionalcode_id_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatepromocionalcode',
            name='id_servico',
        ),
        migrations.AddField(
            model_name='codigos_promocionais',
            name='id_servico',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
