# Generated by Django 2.2.5 on 2020-09-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigos_promocionais', '0005_auto_20200922_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigos_promocionais',
            name='id_servico',
        ),
    ]
