# Generated by Django 2.2.5 on 2020-09-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos_promocionais', '0006_remove_codigos_promocionais_id_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigos_promocionais',
            name='id_servico',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
